### ISSUE TITLE
A problem while make accelerators

### ISSUE THREAD

**Issue by azurezene** [diamantopoulos/memluv#1]
Hi，your design introduced in the paper is so interesting.
I met some problems when trying to compile the project: I run the command **_make accelerators_**,but end up with this error

> /memluv/src/memluv.c:170: undefined reference to `log2'
> collect2: error: ld returned 1 exit status
> make[3]: *** [src/CMakeFiles/test_memluv.dir/build.make:85: src/test_memluv] Error 1
> make[2]: *** [CMakeFiles/Makefile2:466: src/CMakeFiles/test_memluv.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:419: src/CMakeFiles/accelerators.dir/rule] Error 2
> make: *** [Makefile:209: accelerators] Error 2

thank you for your help.

**Comment by diamantopoulos** [comment]
Hi @AzzHub, thanks for your interest in the library. I cannot replicate your problem on my side. Probably it is related the system you try to compile which cannot link the math.h library? I've tried to check the lib in cmake and force the linking in [3398cd8](https://github.com/diamantopoulos/memluv/commit/3398cd81695d1ba492e10a0f55c1e576bffec591). Cheers

**Comment by azurezene** [comment]
I run the code after commenting the line refering to <math.h>.This is not a fine way.
Thanks for your help.
